# type: ignore
import sys
from typing import Literal, List, Any, Optional, Tuple, Dict
import numpy as np
import enum
import numpy

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# <litgen_stub> // Autogenerated code below! Do not edit!
####################    <generated_from:AKSeries.hpp>    ####################
# #ifndef __AK_SERIES_INTERFACE
#

class Motor:
    pass

class MitModeMotor(Motor):
    def send_and_recieve(self, param_0: MitRunSettings) -> Optional[MitRecvFrame]:
        pass

    def send(self, param_0: MitRunSettings) -> None:
        pass

class ServoModeMotor(Motor):
    def send_duty_cycle(self, duty_cycle: float) -> None:
        pass

    def send_current_loop(self, current_loop: float) -> None:
        pass

    def send_current_brake(self, current: float) -> None:
        pass

    def send_rpm(self, rpm: float) -> None:
        pass

    def send_position(self, pos: float) -> None:
        pass

    def send_origin(self, origin_mode: int) -> None:
        pass

    def send_position_and_velo(
        self, position: float, speed: float, accel: float
    ) -> None:
        pass

class AKSeriesInterface:
    @overload
    def __init__(self, canif: str) -> None:
        pass

    @overload
    def create_mit_motor(self, param_0: AKSeriesMotor, param_1: int) -> MitModeMotor:
        pass

    @overload
    def create_mit_motor(self, param_0: MotorRunLimits, param_1: int) -> MitModeMotor:
        pass

    @overload
    def create_servo_motor(
        self, param_0: AKSeriesMotor, param_1: int
    ) -> ServoModeMotor:
        pass

    @overload
    def create_servo_motor(
        self, param_0: MotorRunLimits, param_1: int
    ) -> ServoModeMotor:
        pass

    def read_servo_frame(self) -> Optional[ServoRecvFrame]:
        pass

# #endif
#
####################    </generated_from:AKSeries.hpp>    ####################

# </litgen_stub> // Autogenerated code end!
