#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/functional.h>
#include <pybind11/numpy.h>

#include "AKSeries.hpp"

namespace py = pybind11;

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// <litgen_glue_code>  // Autogenerated code below! Do not edit!

// </litgen_glue_code> // Autogenerated code end
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


void py_init_module_AKSeriesOut(py::module& m)
{
    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    // <litgen_pydef> // Autogenerated code below! Do not edit!
    ////////////////////    <generated_from:AKSeries.hpp>    ////////////////////
    // #ifndef __AK_SERIES_INTERFACE
    //


    auto pyClassMotor =
        py::class_<AKSeries::Motor>
            (m, "Motor", "")
        // (default constructor explicitly deleted)
        ;


    auto pyClassMitModeMotor =
        py::class_<AKSeries::MitModeMotor, AKSeries::Motor>
            (m, "MitModeMotor", "")
        // (default constructor explicitly deleted)
        .def("send_and_recieve",
            &AKSeries::MitModeMotor::sendAndRecieve, py::arg("param_0"))
        .def("send",
            &AKSeries::MitModeMotor::send, py::arg("param_0"))
        ;


    auto pyClassServoModeMotor =
        py::class_<AKSeries::ServoModeMotor, AKSeries::Motor>
            (m, "ServoModeMotor", "")
        // (default constructor explicitly deleted)
        .def("send_duty_cycle",
            &AKSeries::ServoModeMotor::sendDutyCycle, py::arg("duty_cycle"))
        .def("send_current_loop",
            &AKSeries::ServoModeMotor::sendCurrentLoop, py::arg("current_loop"))
        .def("send_current_brake",
            &AKSeries::ServoModeMotor::sendCurrentBrake, py::arg("current"))
        .def("send_rpm",
            &AKSeries::ServoModeMotor::sendRPM, py::arg("rpm"))
        .def("send_position",
            &AKSeries::ServoModeMotor::sendPosition, py::arg("pos"))
        .def("send_origin",
            &AKSeries::ServoModeMotor::sendOrigin, py::arg("origin_mode"))
        .def("send_position_and_velo",
            &AKSeries::ServoModeMotor::sendPositionAndVelo, py::arg("position"), py::arg("speed"), py::arg("accel"))
        ;


    auto pyClassAKSeriesInterface =
        py::class_<AKSeries::AKSeriesInterface>
            (m, "AKSeriesInterface", "")
        // (default constructor explicitly deleted)
        .def(py::init<const char *>(),
            py::arg("canif"))
        .def("create_mit_motor",
            py::overload_cast<const AKSeriesMotor, uint32_t>(&AKSeries::AKSeriesInterface::createMitMotor), py::arg("param_0"), py::arg("param_1"))
        .def("create_mit_motor",
            py::overload_cast<const MotorRunLimits *, uint32_t>(&AKSeries::AKSeriesInterface::createMitMotor), py::arg("param_0"), py::arg("param_1"))
        .def("create_servo_motor",
            py::overload_cast<const AKSeriesMotor, uint32_t>(&AKSeries::AKSeriesInterface::createServoMotor), py::arg("param_0"), py::arg("param_1"))
        .def("create_servo_motor",
            py::overload_cast<const MotorRunLimits *, uint32_t>(&AKSeries::AKSeriesInterface::createServoMotor), py::arg("param_0"), py::arg("param_1"))
        .def("read_servo_frame",
            &AKSeries::AKSeriesInterface::readServoFrame)
        ;
    // #endif
    //
    ////////////////////    </generated_from:AKSeries.hpp>    ////////////////////

    // </litgen_pydef> // Autogenerated code end
    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
}
