name: tests
run-name: testing by ${{ github.actor }}

on:
  push:
    branches:
      - main
    paths:
      - "include/**"
      - "src/**"
      - "tests/**"

  pull_request:
    branches:
      - main
    paths:
      - "include/**"
      - "src/**"
      - "tests/**"

permissions:
  contents: write

jobs:
  run-tests:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake can-utils libsocketcan-dev libgtest-dev
          sudo modprobe can
          sudo modprobe can_raw

      - name: Run tests
        run: |
          cmake -S . -B build -DSETUP_TEST_IFNAME=ON -DBUILD_TESTING=ON 
          cd build
          make
          # need this to escalate user so we can run all necessary can utils
          sudo ctest || ${cat Testing/Temporary/LastTest.log}
          cd ..
          rm -rf build
